// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyTemplate(arg1:main.ProjectTemplate,arg2:string):Promise<main.Project>;

export function CheckForUpdates():Promise<main.ReleaseCheck>;

export function CheckProject(arg1:main.Project,arg2:string):Promise<main.StartupReport>;

export function CloseTerminal(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function DetectFrontend(arg1:string):Promise<main.FrontendConfig>;

export function DetectProject(arg1:string):Promise<main.Detection>;

export function ExportProjectTemplate(arg1:main.Project):Promise<string>;

export function GetBuildInfo():Promise<main.BuildInfo>;

export function GetCodexOptions(arg1:string):Promise<main.CodexOptions>;

export function GetDesktopSettings():Promise<main.DesktopSettings>;

export function GetEditorSettings(arg1:string):Promise<main.EditorSettings>;

export function GetGitChanges(arg1:string):Promise<main.GitChanges>;

export function GetGitFileDiff(arg1:string,arg2:string,arg3:string):Promise<main.GitFileDiff>;

export function GetLogs(arg1:string):Promise<Array<main.LogLine>>;

export function GetProcessMetrics():Promise<Array<main.ProcessMetrics>>;

export function GetStatuses():Promise<Array<main.Status>>;

export function GetTerminalOutput(arg1:string):Promise<main.TerminalSnapshot>;

export function GetTerminals():Promise<Array<main.TerminalInfo>>;

export function HideToTray():Promise<void>;

export function ListProjects():Promise<Array<main.Project>>;

export function ListRunHistory(arg1:string):Promise<Array<main.RunRecord>>;

export function ListTemplates():Promise<Array<main.ProjectTemplate>>;

export function NewTerminal(arg1:string,arg2:number,arg3:number):Promise<main.TerminalInfo>;

export function OpenCodexAnalysis(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string):Promise<main.TerminalInfo>;

export function OpenSourceInIDEA(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function PickConfigFile():Promise<string>;

export function PickDirectory():Promise<string>;

export function PickIDEAPath():Promise<string>;

export function PickToolFile():Promise<string>;

export function QuitApplication():Promise<void>;

export function ReadIDEAConfigurations(arg1:string):Promise<main.IDEAImport>;

export function ReadRunHistory(arg1:string):Promise<main.RunRecord>;

export function ReadTemplateFile():Promise<Array<main.ProjectTemplate>>;

export function RebuildProject(arg1:string):Promise<void>;

export function ReorderProjects(arg1:Array<string>):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartProject(arg1:string):Promise<void>;

export function RestartService(arg1:string):Promise<void>;

export function RunHistoryText(arg1:string):Promise<string>;

export function SaveDesktopSettings(arg1:main.DesktopSettings):Promise<void>;

export function SaveProject(arg1:main.Project):Promise<main.Project>;

export function SaveTemplate(arg1:main.Project,arg2:string):Promise<main.ProjectTemplate>;

export function SetIDEAPath(arg1:string):Promise<void>;

export function StartProject(arg1:string):Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StopProject(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
