// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyTemplate(arg1, arg2) {
  return window['go']['main']['App']['ApplyTemplate'](arg1, arg2);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CheckProject(arg1, arg2) {
  return window['go']['main']['App']['CheckProject'](arg1, arg2);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function DetectFrontend(arg1) {
  return window['go']['main']['App']['DetectFrontend'](arg1);
}

export function DetectProject(arg1) {
  return window['go']['main']['App']['DetectProject'](arg1);
}

export function ExportProjectTemplate(arg1) {
  return window['go']['main']['App']['ExportProjectTemplate'](arg1);
}

export function GetBuildInfo() {
  return window['go']['main']['App']['GetBuildInfo']();
}

export function GetCodexOptions(arg1) {
  return window['go']['main']['App']['GetCodexOptions'](arg1);
}

export function GetDesktopSettings() {
  return window['go']['main']['App']['GetDesktopSettings']();
}

export function GetEditorSettings(arg1) {
  return window['go']['main']['App']['GetEditorSettings'](arg1);
}

export function GetGitChanges(arg1) {
  return window['go']['main']['App']['GetGitChanges'](arg1);
}

export function GetGitFileDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetGitFileDiff'](arg1, arg2, arg3);
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetProcessMetrics() {
  return window['go']['main']['App']['GetProcessMetrics']();
}

export function GetStatuses() {
  return window['go']['main']['App']['GetStatuses']();
}

export function GetTerminalOutput(arg1) {
  return window['go']['main']['App']['GetTerminalOutput'](arg1);
}

export function GetTerminals() {
  return window['go']['main']['App']['GetTerminals']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListRunHistory(arg1) {
  return window['go']['main']['App']['ListRunHistory'](arg1);
}

export function ListTemplates() {
  return window['go']['main']['App']['ListTemplates']();
}

export function NewTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['NewTerminal'](arg1, arg2, arg3);
}

export function OpenCodexAnalysis(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['OpenCodexAnalysis'](arg1, arg2, arg3, arg4, arg5);
}

export function OpenSourceInIDEA(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OpenSourceInIDEA'](arg1, arg2, arg3, arg4);
}

export function PickConfigFile() {
  return window['go']['main']['App']['PickConfigFile']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickIDEAPath() {
  return window['go']['main']['App']['PickIDEAPath']();
}

export function PickToolFile() {
  return window['go']['main']['App']['PickToolFile']();
}

export function QuitApplication() {
  return window['go']['main']['App']['QuitApplication']();
}

export function ReadIDEAConfigurations(arg1) {
  return window['go']['main']['App']['ReadIDEAConfigurations'](arg1);
}

export function ReadRunHistory(arg1) {
  return window['go']['main']['App']['ReadRunHistory'](arg1);
}

export function ReadTemplateFile() {
  return window['go']['main']['App']['ReadTemplateFile']();
}

export function RebuildProject(arg1) {
  return window['go']['main']['App']['RebuildProject'](arg1);
}

export function ReorderProjects(arg1) {
  return window['go']['main']['App']['ReorderProjects'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartProject(arg1) {
  return window['go']['main']['App']['RestartProject'](arg1);
}

export function RestartService(arg1) {
  return window['go']['main']['App']['RestartService'](arg1);
}

export function RunHistoryText(arg1) {
  return window['go']['main']['App']['RunHistoryText'](arg1);
}

export function SaveDesktopSettings(arg1) {
  return window['go']['main']['App']['SaveDesktopSettings'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SaveTemplate(arg1, arg2) {
  return window['go']['main']['App']['SaveTemplate'](arg1, arg2);
}

export function SetIDEAPath(arg1) {
  return window['go']['main']['App']['SetIDEAPath'](arg1);
}

export function StartProject(arg1) {
  return window['go']['main']['App']['StartProject'](arg1);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopProject(arg1) {
  return window['go']['main']['App']['StopProject'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
