// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteProject(arg1:string):Promise<void>;

export function DetectFrontend(arg1:string):Promise<main.FrontendConfig>;

export function DetectProject(arg1:string):Promise<main.Detection>;

export function GetLogs(arg1:string):Promise<Array<main.LogLine>>;

export function GetStatuses():Promise<Array<main.Status>>;

export function ListProjects():Promise<Array<main.Project>>;

export function PickConfigFile():Promise<string>;

export function PickDirectory():Promise<string>;

export function PickToolFile():Promise<string>;

export function RebuildProject(arg1:string):Promise<void>;

export function RestartProject(arg1:string):Promise<void>;

export function SaveProject(arg1:main.Project):Promise<main.Project>;

export function StartProject(arg1:string):Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StopProject(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<void>;
