// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseTerminal(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DetectFrontend(arg1:string):Promise<main.FrontendConfig>;

export function DetectProject(arg1:string):Promise<main.Detection>;

export function GetCodexOptions(arg1:string):Promise<main.CodexOptions>;

export function GetGitChanges(arg1:string):Promise<main.GitChanges>;

export function GetGitFileDiff(arg1:string,arg2:string,arg3:string):Promise<main.GitFileDiff>;

export function GetLogs(arg1:string):Promise<Array<main.LogLine>>;

export function GetStatuses():Promise<Array<main.Status>>;

export function GetTerminalOutput(arg1:string):Promise<main.TerminalSnapshot>;

export function GetTerminals():Promise<Array<main.TerminalInfo>>;

export function ListProjects():Promise<Array<main.Project>>;

export function NewTerminal(arg1:string,arg2:number,arg3:number):Promise<main.TerminalInfo>;

export function OpenCodexAnalysis(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string):Promise<main.TerminalInfo>;

export function PickConfigFile():Promise<string>;

export function PickDirectory():Promise<string>;

export function PickToolFile():Promise<string>;

export function ReadIDEAConfigurations(arg1:string):Promise<main.IDEAImport>;

export function RebuildProject(arg1:string):Promise<void>;

export function ReorderProjects(arg1:Array<string>):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartProject(arg1:string):Promise<void>;

export function SaveProject(arg1:main.Project):Promise<main.Project>;

export function StartProject(arg1:string):Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StopProject(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
