// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DetectFrontend(arg1) {
  return window['go']['main']['App']['DetectFrontend'](arg1);
}

export function DetectProject(arg1) {
  return window['go']['main']['App']['DetectProject'](arg1);
}

export function GetCodexOptions(arg1) {
  return window['go']['main']['App']['GetCodexOptions'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetStatuses() {
  return window['go']['main']['App']['GetStatuses']();
}

export function GetTerminalOutput(arg1) {
  return window['go']['main']['App']['GetTerminalOutput'](arg1);
}

export function GetTerminals() {
  return window['go']['main']['App']['GetTerminals']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function NewTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['NewTerminal'](arg1, arg2, arg3);
}

export function OpenCodexAnalysis(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['OpenCodexAnalysis'](arg1, arg2, arg3, arg4, arg5);
}

export function PickConfigFile() {
  return window['go']['main']['App']['PickConfigFile']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickToolFile() {
  return window['go']['main']['App']['PickToolFile']();
}

export function RebuildProject(arg1) {
  return window['go']['main']['App']['RebuildProject'](arg1);
}

export function ReorderProjects(arg1) {
  return window['go']['main']['App']['ReorderProjects'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartProject(arg1) {
  return window['go']['main']['App']['RestartProject'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function StartProject(arg1) {
  return window['go']['main']['App']['StartProject'](arg1);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopProject(arg1) {
  return window['go']['main']['App']['StopProject'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
